## Ejercicio final
 Dado que en este verano va a hacer mucho calor, me quiero comprar un aire acondicionado. Pero primero, necesito conocer la cantidad de frigorias necesarias para refrescar la habitación de mi casa.

Una fórmula rápida para cálcular las frigorias necesarias es multiplicar el volúmen de la habitación por 50 frigorías por m3.

Crea una función que calcule y retorne las frigorias necesarias, a partir de las medidas de la habitación, alto, ancho, y profundiad.